- name: say 'hello world'
  hosts: all
  tasks:

    - name: echo 'hello world'
      command: echo 'hello world'
      register: result

    - name: print stdout
      debug:
        msg: "{{ result.stdout }}"
    
    - name: ls all files
      command: ls -al
      register: result_ls
    - name: ls all files
      debug:
          msg: "{{ result_ls.stdout }}"
